name = "kokoro-web"
main = "src/index.ts" # or index.js
compatibility_date = "2025-06-01"

[container]
binding = "KOKORO_CONTAINER"
image = "ghcr.io/eduardolat/kokoro-web:latest"

[[container.env]]
name = "KW_SECRET_API_KEY"
value = "your-secret-api-key"
