name = "kokoro-web"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[durable_objects]
bindings = [
  { name = "KOKORO_CONTAINER", class_name = "KokoroContainer" }
]

[[migrations]]
tag = "v1"
new_classes = ["KokoroContainer"]

[[r2_buckets]]
binding = "AUDIO_JOBS_BUCKET"
bucket_name = "kokoro-audio-jobs"
preview_bucket_name = "kokoro-audio-jobs"

[containers]
app = [
  { name = "KOKORO_CONTAINER", instances = 1, configuration = { image = "ghcr.io/eduardolat/kokoro-web:latest" } }
]
